import { type RouterOutputs, api } from "@/utils/api";
import Spinner from "@/components/Spinner";

import Head from "next/head";
import Link from "next/link";

import { UserButton, useUser } from "@clerk/nextjs";

import dayjs from "dayjs";
import relatveTime from "dayjs/plugin/relativeTime";
import Image from "next/image";
dayjs.extend(relatveTime);

function CreatePostWizard() {
  const { user } = useUser();
  if (!user) return null;

  return (
    <div className="flex w-full gap-4">
      <img
        src={user.imageUrl}
        alt={`${user.fullName}'s profile image`}
        className="h-12 w-12 rounded-full"
      />

      <input
        placeholder="type some emojis"
        className="grow bg-transparent outline-none"
      />
    </div>
  );
}

type PostWithUser = RouterOutputs["posts"]["getAll"][number];

function PostView(props: PostWithUser) {
  const { post, user } = props;

  return (
    <div
      key={post.id}
      className="flex items-center gap-4 border-b border-slate-400 p-4"
    >
      <Image
        src={user.imageUrl}
        alt={`${user.username}'s profile image`}
        width={48}
        height={48}
        className="h-12 w-12 rounded-full"
      />
      <div className="flex flex-col">
        <span className="text-slate-400">
          {`@${user.username}`} {`${dayjs(post.createdAt).fromNow()}`}
        </span>
        <span>{post.content}</span>
      </div>
    </div>
  );
}

function Feed() {
  const { data, isLoading: postsLoading } = api.posts.getAll.useQuery();

  if (postsLoading) return <LoadingPage />;
  if (!data) return <div>Something went wrong</div>;

  return (
    <section>
      {[...data, ...data].map((props) => (
        <PostView {...props} key={props.post.id} />
      ))}
    </section>
  );
}

export default function Home() {
  api.posts.getAll.useQuery();

  const { isLoaded: userLoaded, isSignedIn } = useUser();
  if (!userLoaded) return <div />;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen justify-center">
        <div className="w-full border-x border-slate-400 md:max-w-2xl">
          <section className="flex border-b border-slate-400 p-4">
            {!isSignedIn ? (
              <>
                <Link href="sign-in">Sign In</Link>
                <Link href="sign-up">Sign Up</Link>
              </>
            ) : (
              <>
                <UserButton afterSignOutUrl="/" />
                <CreatePostWizard />
              </>
            )}
          </section>
          <Feed />
        </div>
      </main>
    </>
  );
}

export function LoadingPage() {
  return (
    <div className="flex h-24 w-full items-center justify-center">
      <Spinner />
    </div>
  );
}
